### ISSUE TITLE
Functional test of FicTrac

### ISSUE THREAD

**Issue by floesche** [reiserlab/Component-Designs#12]
Try to set up a working version of FicTrac in parallel to reading [the paper](https://doi.org/10.1016/j.jneumeth.2014.01.010).

**Comment by floesche** [comment]
Just moved this from [Week 3](https://github.com/reiserlab/Component-Designs/milestone/2).

**Comment by InchoateArtichoke** [comment]
Small issue w/ installing vcpkg dependencies, where ffmpeg build failed; caused by me having only Visual Studio and no SDK installed.

**Comment by InchoateArtichoke** [comment]
Update: I was wrong about this. Turns out the issue may have been an incompatible version of vcpkg. Used installer at https://www.reddit.com/r/fictrac/comments/j5k89u/fictrac_installer_for_version_211/

**Comment by floesche** [comment]
That version from reddit looks like it is a binary package for the FLIR cameras (Spinnaker is only needed for FLIR, not for the PS3 camera). Since we might need to change some code, it would make sense to build Fictrac instead of using a pre-compiled version.

If you would follow the installation steps at https://github.com/rjdmoore/fictrac#installation, where does do you start seeing errors?

**Comment by InchoateArtichoke** [comment]
Per people's insight online, tried with older version of cmake (3.20.5) and older commits of vcpkg, but error persisted. Currently on cmake 3.20.5 and a commit of vcpkg from 10-ish days ago (last time opencv was edited). Generates error log below:

> C:\Users\ajian\Documents\GitHub\vcpkg>.\vcpkg install ffmpeg[x264]:x64-windows
> Computing installation plan...
> The following packages will be built and installed:
>     ffmpeg[avcodec,avdevice,avfilter,avformat,core,gpl,postproc,swresample,swscale,x264]:x64-windows -> 4.4#5
> Detecting compiler hash for triplet x64-windows...
> Could not locate cached archive: C:\Users\ajian\AppData\Local\vcpkg\archives\ea\ea3bda633c3150faf0a119fe2d6e961b1b964f23.zip
> Starting package 1/1: ffmpeg:x64-windows
> Building package ffmpeg[avcodec,avdevice,avfilter,avformat,core,gpl,postproc,swresample,swscale,x264]:x64-windows...
> -- Using C:/Users/ajian/Documents/GitHub/vcpkg/downloads/ffmpeg-ffmpeg-n4.4.tar.gz
> -- Cleaning sources at C:/Users/ajian/Documents/GitHub/vcpkg/buildtrees/ffmpeg/src/n4.4-5002d86a54.clean. Use --editable to skip cleaning for the packages you specify.
> -- Using source at C:/Users/ajian/Documents/GitHub/vcpkg/buildtrees/ffmpeg/src/n4.4-5002d86a54.clean
> -- Using msys root at C:/Users/ajian/Documents/GitHub/vcpkg/downloads/tools/msys2/aaafe87dcead272e
> -- Building Options: --toolchain=msvc --enable-pic --disable-doc --enable-debug --enable-runtime-cpudetect --enable-asm --enable-x86asm --enable-gpl --disable-ffmpeg --disable-ffplay --disable-ffprobe --enable-avcodec --enable-avdevice --enable-avformat --enable-avfilter --enable-postproc --enable-swresample --enable-swscale --disable-libass --disable-avisynth --disable-bzlib --disable-libdav1d --disable-libfdk-aac --disable-libfontconfig --disable-libfreetype --disable-libfribidi --disable-iconv --disable-libilbc --disable-lzma --disable-libmp3lame --disable-libmodplug --disable-cuda --disable-nvenc --disable-nvdec  --disable-cuvid --disable-ffnvcodec --disable-opencl --disable-opengl --disable-libopenh264 --disable-libopenjpeg --disable-openssl --disable-libopus --disable-sdl2 --disable-libsnappy --disable-libsoxr --disable-libspeex --disable-libssh --disable-libtensorflow --disable-libtesseract --disable-libtheora --disable-libvorbis --disable-libvpx --disable-libwebp --enable-libx264 --disable-libx265 --disable-libxml2 --disable-zlib  --disable-static --enable-shared --extra-cflags=-DHAVE_UNISTD_H=0
> -- Building Release Options:  --extra-cflags=-MD --extra-cxxflags=-MD
> -- Building ffmpeg for Release
> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
>     Command failed: C:/Users/ajian/Documents/GitHub/vcpkg/downloads/tools/msys2/aaafe87dcead272e/usr/bin/bash.exe ./build.sh
>     Working Directory: C:/Users/ajian/Documents/GitHub/vcpkg/buildtrees/ffmpeg/x64-windows-rel
>     Error code: 127
>     See logs for more information:
>       C:\Users\ajian\Documents\GitHub\vcpkg\buildtrees\ffmpeg\build-x64-windows-rel-out.log
>       C:\Users\ajian\Documents\GitHub\vcpkg\buildtrees\ffmpeg\build-x64-windows-rel-err.log
> 
> Call Stack (most recent call first):
>   ports/ffmpeg/portfile.cmake:632 (vcpkg_execute_required_process)
>   scripts/ports.cmake:139 (include)
> 
> 
> Error: Building package ffmpeg:x64-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: ffmpeg:x64-windows
>   Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9
> 
> Additionally, attach any relevant sections from the log files above.

**Comment by InchoateArtichoke** [comment]
OK, I'm not entirely sure what happened, but it seems to be working now.

What I did: forgot I ran the ffmpeg install command, came back a day later, hit "enter", and installation finished.

> -- Building Release Options:  --extra-cflags=-MD --extra-cxxflags=-MD
> -- Building ffmpeg for Release _formerly frozen here, pressing a key moved it on_
> -- Building Debug Options: --debug --extra-cflags=-MDd --extra-cxxflags=-MDd
> -- Building ffmpeg for Debug
> -- Generating C:\Users\ajian\Documents\GitHub\vcpkg\packages\ffmpeg_x64-windows\debug\lib\avcodec.lib
> -- Generating C:\Users\ajian\Documents\GitHub\vcpkg\packages\ffmpeg_x64-windows\debug\lib\avdevice.lib
> -- Generating C:\Users\ajian\Documents\GitHub\vcpkg\packages\ffmpeg_x64-windows\debug\lib\avfilter.lib
> -- Generating C:\Users\ajian\Documents\GitHub\vcpkg\packages\ffmpeg_x64-windows\debug\lib\avformat.lib
> -- Generating C:\Users\ajian\Documents\GitHub\vcpkg\packages\ffmpeg_x64-windows\debug\lib\avutil.lib
> -- Generating C:\Users\ajian\Documents\GitHub\vcpkg\packages\ffmpeg_x64-windows\debug\lib\postproc.lib
> -- Generating C:\Users\ajian\Documents\GitHub\vcpkg\packages\ffmpeg_x64-windows\debug\lib\swresample.lib
> -- Generating C:\Users\ajian\Documents\GitHub\vcpkg\packages\ffmpeg_x64-windows\debug\lib\swscale.lib
> -- Generating C:\Users\ajian\Documents\GitHub\vcpkg\packages\ffmpeg_x64-windows\lib\avcodec.lib
> -- Generating C:\Users\ajian\Documents\GitHub\vcpkg\packages\ffmpeg_x64-windows\lib\avdevice.lib
> -- Generating C:\Users\ajian\Documents\GitHub\vcpkg\packages\ffmpeg_x64-windows\lib\avfilter.lib
> -- Generating C:\Users\ajian\Documents\GitHub\vcpkg\packages\ffmpeg_x64-windows\lib\avformat.lib
> -- Generating C:\Users\ajian\Documents\GitHub\vcpkg\packages\ffmpeg_x64-windows\lib\avutil.lib
> -- Generating C:\Users\ajian\Documents\GitHub\vcpkg\packages\ffmpeg_x64-windows\lib\postproc.lib
> -- Generating C:\Users\ajian\Documents\GitHub\vcpkg\packages\ffmpeg_x64-windows\lib\swresample.lib
> -- Generating C:\Users\ajian\Documents\GitHub\vcpkg\packages\ffmpeg_x64-windows\lib\swscale.lib
> -- Using msys root at C:/Users/ajian/Documents/GitHub/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8
> -- Fixing pkgconfig file: C:/Users/ajian/Documents/GitHub/vcpkg/packages/ffmpeg_x64-windows/lib/pkgconfig/libavcodec.pc
> -- Fixing pkgconfig file: C:/Users/ajian/Documents/GitHub/vcpkg/packages/ffmpeg_x64-windows/lib/pkgconfig/libavdevice.pc
> -- Fixing pkgconfig file: C:/Users/ajian/Documents/GitHub/vcpkg/packages/ffmpeg_x64-windows/lib/pkgconfig/libavfilter.pc
> -- Fixing pkgconfig file: C:/Users/ajian/Documents/GitHub/vcpkg/packages/ffmpeg_x64-windows/lib/pkgconfig/libavformat.pc
> -- Fixing pkgconfig file: C:/Users/ajian/Documents/GitHub/vcpkg/packages/ffmpeg_x64-windows/lib/pkgconfig/libavutil.pc
> -- Fixing pkgconfig file: C:/Users/ajian/Documents/GitHub/vcpkg/packages/ffmpeg_x64-windows/lib/pkgconfig/libpostproc.pc
> -- Fixing pkgconfig file: C:/Users/ajian/Documents/GitHub/vcpkg/packages/ffmpeg_x64-windows/lib/pkgconfig/libswresample.pc
> -- Fixing pkgconfig file: C:/Users/ajian/Documents/GitHub/vcpkg/packages/ffmpeg_x64-windows/lib/pkgconfig/libswscale.pc
> -- Fixing pkgconfig file: C:/Users/ajian/Documents/GitHub/vcpkg/packages/ffmpeg_x64-windows/debug/lib/pkgconfig/libavcodec.pc
> -- Fixing pkgconfig file: C:/Users/ajian/Documents/GitHub/vcpkg/packages/ffmpeg_x64-windows/debug/lib/pkgconfig/libavdevice.pc
> -- Fixing pkgconfig file: C:/Users/ajian/Documents/GitHub/vcpkg/packages/ffmpeg_x64-windows/debug/lib/pkgconfig/libavfilter.pc
> -- Fixing pkgconfig file: C:/Users/ajian/Documents/GitHub/vcpkg/packages/ffmpeg_x64-windows/debug/lib/pkgconfig/libavformat.pc
> -- Fixing pkgconfig file: C:/Users/ajian/Documents/GitHub/vcpkg/packages/ffmpeg_x64-windows/debug/lib/pkgconfig/libavutil.pc
> -- Fixing pkgconfig file: C:/Users/ajian/Documents/GitHub/vcpkg/packages/ffmpeg_x64-windows/debug/lib/pkgconfig/libpostproc.pc
> -- Fixing pkgconfig file: C:/Users/ajian/Documents/GitHub/vcpkg/packages/ffmpeg_x64-windows/debug/lib/pkgconfig/libswresample.pc
> -- Fixing pkgconfig file: C:/Users/ajian/Documents/GitHub/vcpkg/packages/ffmpeg_x64-windows/debug/lib/pkgconfig/libswscale.pc
> -- Using msys root at C:/Users/ajian/Documents/GitHub/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8
> Dependencies (release):
> Dependencies (debug):
> -- Installing: C:/Users/ajian/Documents/GitHub/vcpkg/packages/ffmpeg_x64-windows/share/ffmpeg/copyright
> -- Performing post-build validation
> -- Performing post-build validation done
> Stored binary cache: C:\Users\ajian\AppData\Local\vcpkg\archives\ea\ea3bda633c3150faf0a119fe2d6e961b1b964f23.zip
> Building package ffmpeg[avcodec,avdevice,avfilter,avformat,core,gpl,postproc,swresample,swscale,x264]:x64-windows... done
> Installing package ffmpeg[avcodec,avdevice,avfilter,avformat,core,gpl,postproc,swresample,swscale,x264]:x64-windows...
> Installing package ffmpeg[avcodec,avdevice,avfilter,avformat,core,gpl,postproc,swresample,swscale,x264]:x64-windows... done
> Elapsed time for package ffmpeg:x64-windows: 23.56 h
> 
> Total elapsed time: 23.56 h

**Comment by floesche** [comment]
This works.
