### ISSUE TITLE
convert walking setup order to non-redundant data storage

### ISSUE THREAD

**Issue by floesche** [reiserlab/Component-Designs#13]
Change the format of walkingsetup_order.csv to be similar to tethering_order.csv. This might include changing the liquid template in Inexpensive-Treadmill.md

The goal is to not have any redundant information in the csv without loosing information on the website.

**Comment by InchoateArtichoke** [comment]
Just pushed changes w/ second table. There was a wonky issue where it refused to call the "Name" column, but resetting the file with a clone cured that for some reason. Also updated both tables to have M3 screws.
