### ISSUE TITLE
Build Full Setup

### ISSUE THREAD

**Issue by InchoateArtichoke** [reiserlab/Component-Designs#14]
Mount all components for walking and tethering setups on baseplate.

**Comment by InchoateArtichoke** [comment]
Acrylic side pieces for hand rest were excessively strained and broke during assembly. I think I've traced the issue to an error in the svg file:

![image](https://user-images.githubusercontent.com/51932963/124013823-a5ce9380-d997-11eb-9141-f5059e501aa9.png)

I believe the large slot should be flush with the indent on the side of the piece? Both sides of the setup have the same issue and the piece does not slot correctly in the base:

![image](https://user-images.githubusercontent.com/51932963/124014386-4f158980-d998-11eb-9fd5-dd5356680211.png)

**Comment by floesche** [comment]
Is it also possible, that the vertical cut in the two side panes is too narrow for the width of the acrylic plate?

**Comment by InchoateArtichoke** [comment]
I think all the slots and mortises/tenons are dimensioned properly, insofar as things mesh well/friction fit. Seems like the misalignment was the driving issue.

**Comment by floesche** [comment]
OK, thanks. I now visually aligned the parts.

Baseplate:
![Baseplate](https://user-images.githubusercontent.com/1568893/124058005-8a46a580-d9f6-11eb-83ba-c5646909510e.png)

Old wall:
![Old wall](https://user-images.githubusercontent.com/1568893/124058095-b3673600-d9f6-11eb-9bfb-5d4c337cc34d.png)

New wall:
![New wall](https://user-images.githubusercontent.com/1568893/124058111-bb26da80-d9f6-11eb-8b2a-03ff605b2ac9.png)

In a695052256c9376a75f2ac8d2679d13a3539c33f I have also removed more double lines, unnecessary screw holes in the baseplate to improve stability, and the cut out from the vertical wall under the hand rest. That latter step should reduce the airflow towards the experimenter, maybe reducing some potential issues with flies blown off the sarcophagus.

Could you please check if these changes make sense, based on the parts that were previously cut?

Also, where did the acrylic break? Maybe we can change the design to avoid this in the future?

**Comment by InchoateArtichoke** [comment]
For posterity: acrylic broke near the top of different vertical slots on both pieces, towards the thinner sides. Should be a non-issue with properly aligned design.

**Comment by floesche** [comment]
Just for completeness: if you could add a picture of the setup to document that the task is done, that would be amazing and we could close the issue?

**Comment by InchoateArtichoke** [comment]
3D printed parts all fit, just waiting on acrylic redesign to ship


![image](https://user-images.githubusercontent.com/51932963/124967119-e900b600-dfd8-11eb-8b95-79e0df4a9653.png)
![Uploading image.png…]()

**Comment by floesche** [comment]
Looks like the upload of a picture with the experimental setup might not have worked: 

![Screenshot_2021-07-08T13-56-35](https://user-images.githubusercontent.com/1568893/124969181-65ed5900-dff4-11eb-9b84-1d31552f1994.png)

**Comment by InchoateArtichoke** [comment]
Fixed!

**Comment by floesche** [comment]
That looks so amazing in yellow! :-)
