### ISSUE TITLE
Track auto-rotation of sphere via FicTrac

### ISSUE THREAD

**Issue by floesche** [reiserlab/Component-Designs#15]
The goal of this task is to verify that FicTrac is working properly. Some short `*.dat` file would verify that everything works as expected.

To reach this goal, the following steps might be necessary:

- [x] Install FicTrac software
- [x] paint sphere with pattern
- [x] set up sphere holder and air pump
- [x] have the PS3 camera working with IR light
- [x] set up illumination via LED
- [x] configure FicTrac via configGui
- [x] run FicTrac for 5 seconds to record the `*.dat` file

**Comment by InchoateArtichoke** [comment]
Github won't take .dat files, so I converted to .txt:
[test-20210715_084412.txt](https://github.com/reiserlab/Component-Designs/files/6832196/test-20210715_084412.txt)

**Comment by floesche** [comment]
The second to last column in the dat file is the delta timestamp, according to the [fictrac documentation](https://github.com/rjdmoore/fictrac/blob/master/doc/data_header.txt). According to that, each frame lasts about 13.3ms, which means fictrac ran at about 75fps. We need at least twice that speed for reliable tracking.

**Comment by InchoateArtichoke** [comment]
Windows, using Frank's fictrac/pseye branch, with PSEyeDriver installed on top of CLEye.

Without resizing camera:
<img width="960" alt="noresizeerror" src="https://user-images.githubusercontent.com/51932963/127193297-444fe277-540b-4d52-a0f8-343470e278d9.png">

With resizing camera:
<img width="960" alt="winerrorresize" src="https://user-images.githubusercontent.com/51932963/127193302-8cb1be7c-6193-4ed0-9fc9-327658040a7d.png">

**Comment by InchoateArtichoke** [comment]
Autorotation data file:
[fictrac-20210728_084015.txt](https://github.com/reiserlab/Component-Designs/files/6894997/fictrac-20210728_084015.txt)

**Comment by InchoateArtichoke** [comment]
Data file w/ (poorly) tethered fly

[fictrac-20210729_103534.txt](https://github.com/reiserlab/Component-Designs/files/6902478/fictrac-20210729_103534.txt)

**Comment by InchoateArtichoke** [comment]
(belated) screenshot w/ debug window
![Screenshot from 2021-07-29 10-37-18](https://user-images.githubusercontent.com/51932963/127890051-41aed23d-72fa-4c52-98bc-4769effcac03.png)

**Comment by floesche** [comment]
![unnamed](https://user-images.githubusercontent.com/1568893/128383532-df89bd78-af88-4e46-84b1-e4841443100e.png)

This is probably a better screenshot (from your slides presentation).

In both cases the "accumulated map" does not show the full sphere and therefore the tracking isn't reliable yet. Also, this is different from the configuration file I sent you, where the template is taken from a previously recorded image. These discrepancies could possibly explain the noise you are seeing in your data.

In any case, I think the initial task is done now and we can close this issue.
