### ISSUE TITLE
How to improve component list

### ISSUE THREAD

**Issue by floesche** [reiserlab/Component-Designs#7]
From this weeks work it became obvious, that generating a shopping list to replicate the setup is more laborious than I had hoped.

in this issue we can discuss how this could be improved.

**Comment by floesche** [comment]
Would this be a good place: https://reiserlab.github.io/Component-Designs/walking/inexpensive-treadmill ? Would you have expected it at another location when we started earlier this week?

**Comment by InchoateArtichoke** [comment]
I think it's really hard to avoid that page if you're trying to rebuild the setup. So that should be a good place.

**Comment by floesche** [comment]
And would you prefer links on the website, or a spreadsheet that you can download and then edit for your own requirements?

**Comment by floesche** [comment]
Since [links will rot](https://en.wikipedia.org/wiki/Link_rot) over time, we want to avoid duplicating information. Otherwise, if one product becomes unavailable at some point, we would need to change the link at several places and this is error prone…

So if we can find a way to render the content on the website (= Markdown → HTML….) and provide a downloadable file (eg CSV) form the same source, that would be best IMHO. For a start, I'd settle with one of the options.

**Comment by InchoateArtichoke** [comment]
Makes sense, let's go w/ a table on the site then.

**Comment by floesche** [comment]
Could this be interesting? https://docs.github.com/en/github/managing-files-in-a-repository/working-with-non-code-files/rendering-csv-and-tsv-data

**Comment by floesche** [comment]
Another piece of information that looks useful is at https://jekyllrb.com/tutorials/csv-to-table/

Github-pages uses jekyll to render the content of the github repository into a website…

**Comment by InchoateArtichoke** [comment]
Yup, I got that working yesterday to display the csv. It looks pretty nice. 
![image](https://user-images.githubusercontent.com/51932963/122100357-f0f97b80-cdc7-11eb-96b7-0145fb4d44bc.png)

**Comment by InchoateArtichoke** [comment]
I was able to get around the issue I mentioned earlier (not being able to publish the data files) by changing the default data directory, since the default (/_data) starts with an underscore and is ignored by Jekyll in the site urls. The tables and csv downloads should come from the same source now!

Will push page with tables and links once I clean up the csv files.

**Comment by floesche** [comment]
The screenshot looks good.

On the website, we don't need the full link spelled out – so the link could be the name of the vendor, once you click on it you can get to the deep linked URL. 

Also, would it be possible to move the csv into an existing path (eg "assets") to keep the root directory uncluttered? I am sure there are more improvements once the table is on the website… :-)

**Comment by floesche** [comment]
This is the section I was referring to in the meeting: https://jekyllrb.com/tutorials/csv-to-table/#unpack-a-row

With this in mind, you can add one column to the CSV with the component description URL (within our own website) and one column with the supplier URL. For the website rendering, you could  then use the [liquid syntax](https://jekyllrb.com/docs/liquid/) to generate the `<a href…>` anchors.

**Comment by floesche** [comment]
The [result](https://reiserlab.github.io/Component-Designs/inexpensive-treadmill) looks very good and addresses exactly the issues that the previous documentation had. I consider this task done, if we come up with ideas how to improve this, we can open new issues in the future.
