### ISSUE TITLE
Start a step-by-step assembly protocol

### ISSUE THREAD

**Issue by floesche** [reiserlab/Component-Designs#8]
The production of a detailed step-by-step assembly protocol is one of the goals we defined for the project. In this task we find a place where we can develop and disseminate the document.

We talked about different options in the past week. They included just another page on the github page, a protocols.io document, an instructables website, or a preprint. As part of this task, let's set up a test document with a few paragraphs and see how well we can work with it.

**Comment by floesche** [comment]
As discussed: 
 - organize the document into detailed numbered steps (eg 1: Order parts, 1.1 shops, 1.2 Laser cutting 1.3: 3D printing…) and maybe move details for the orientation of models, support etc to an appendix?
 - Maybe split the 3D printing step into two alternatives: either order the parts or produce yourself. 
 - give more details on the printer we used. Then we can also give detailed settings for each printer and document what the outcome looks like (picture of treadmill holder with support vs. no support

**Comment by floesche** [comment]
I think, out of this only the information about the printer you used is really missing. 

For the parts we ordered online, you could add the choice of materials etc, maybe with screenshots?

Other than that, I think this task is almost done.

**Comment by InchoateArtichoke** [comment]
Step by step documentation located at:

https://docs.google.com/document/d/1kanhWL9ZFA6SSYsShQDp2xfjD43P9yL3bMd7HhZYnw4/edit

Print information moved to a print appendix at the end and printer information has been added.
